channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=22.0.4
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - numpy==1.26.2
  - pandas==2.2.2
  - psutil==5.9.0
  - scikit-learn==1.5.2
  - scipy==1.14.1
name: mlflow-env
