name: Fetch and Predict

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Grant permission to write to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Git LFS
        run: git lfs install

      - name: Fetch LFS files
        run: |
          git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        env:
          VC_KEY: ${{ secrets.VC_KEY }}
        run: |
          python air_quality_forecast/get_prediction_data.py

      - name: Commit and push prediction CSV to repository
        run: |
          git config --local user.email "atodorov284@gmail.com"  # Replace with your email
          git config --local user.name "Alex"          # Replace with your name
          git add data/inference/current_prediction_data.csv
          git commit -m "Update prediction data" || echo "No changes to commit"
          git push origin deploy
