name: Fetch and Predict

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Git LFS
        run: git lfs install

      - name: Fetch LFS files
        run: |
          git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        env:
          VC_KEY: ${{ secrets.VC_KEY }}
        run: |
          python air_quality_forecast/get_prediction_data.py

      - name: Upload prediction CSV as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: current-prediction-data
          path: data/inference/current_prediction_data.csv
