name: Sync to Hugging Face hub
on:
  push:
    branches: [deploy]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Git LFS
        run: git lfs install
      - name: Sync history with LFS
        run: git lfs migrate import --include="*.xgb, *.pkl" --yes --everything
      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://03chrisk:${{ secrets.HF }}@huggingface.co/spaces/03chrisk/air-quality-forecasting deploy:main
