name: Running code

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main
      - data_engineering
      - model_development

jobs:
  check-reproducibility:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run setup script
        run: pip3 install -r requirements.txt

      - name: Run main.py
        id: run_main
        run: |
          python3 air-quality-forecast/main.py