name: Style check

on:
  push:
    branches:
      - main

jobs:
  flake8_py3:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.18
          architecture: x64
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Configure Flake8
        run: echo "[flake8]" > .flake8 && echo "extend-ignore = E402" >> .flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: "flake8_py3"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}